let selectedFile = null;

document.getElementById('browseBtn').addEventListener('click', () => {
  document.getElementById('imageInput').click();
});

document.getElementById('imageInput').addEventListener('change', function(event) {
  selectedFile = event.target.files[0];
  displayImagePreview(selectedFile);
});

document.getElementById('dragArea').addEventListener('dragover', (e) => {
  e.preventDefault();
  document.getElementById('dragArea').classList.add('dragover');
});

document.getElementById('dragArea').addEventListener('dragleave', (e) => {
  e.preventDefault();
  document.getElementById('dragArea').classList.remove('dragover');
});

document.getElementById('dragArea').addEventListener('drop', (e) => {
  e.preventDefault();
  document.getElementById('dragArea').classList.remove('dragover');
  selectedFile = e.dataTransfer.files[0];
  displayImagePreview(selectedFile);
});

function displayImagePreview(file) {
  const reader = new FileReader();

  reader.onload = function(e) {
    const img = new Image();
    img.onload = function() {
      const previewArea = document.getElementById('imagePreviewArea');
      previewArea.innerHTML = ""; 
      previewArea.appendChild(img);
    };
    img.src = e.target.result;
  };
  
  reader.readAsDataURL(file);
}

document.getElementById('submitBtn').addEventListener('click', function() {
  if (!selectedFile) {
    alert("Please select an image first.");
    return;
  }
  handleFile(selectedFile);
});

function handleFile(file) {
  const reader = new FileReader();
  reader.onload = function(e) {
    const img = new Image();
    img.onload = function() {
      EXIF.getData(img, function() {
        const allMetaData = EXIF.getAllTags(this);
        displayMetadata(allMetaData);
        if (allMetaData.GPSLatitude && allMetaData.GPSLongitude) {
          const lat = convertDMSToDD(allMetaData.GPSLatitude, allMetaData.GPSLatitudeRef);
          const lon = convertDMSToDD(allMetaData.GPSLongitude, allMetaData.GPSLongitudeRef);
          initializeMap(lat, lon);
        }
      });
    };
    img.src = e.target.result;

    fakeAILookup(file);
  };
  reader.readAsDataURL(file);
}

function displayMetadata(metadata) {
  let output = "<h3>Metadata:</h3><ul>";
  for (let key in metadata) {
    output += `<li><b>${key}:</b> ${metadata[key]}</li>`;
  }
  output += "</ul>";
  document.getElementById('metadata').innerHTML = output;
}

function convertDMSToDD(dms, ref) {
  const degrees = dms[0];
  const minutes = dms[1];
  const seconds = dms[2];
  let dd = degrees + minutes/60 + seconds/3600;
  if (ref === "S" || ref === "W") {
    dd = dd * -1;
  }
  return dd;
}

function fakeAILookup(file) {
  const lookupArea = document.getElementById('ai-lookup');
  lookupArea.innerHTML = "Generating description...";

  setTimeout(() => {
    const fileName = file.name.toLowerCase();
    let description = "An image of something interesting.";

    if (fileName.includes("taj")) description = "An image of the Taj Mahal, India.";
    else if (fileName.includes("beach")) description = "A beautiful beach scenery.";
    else if (fileName.includes("dog")) description = "A cute dog captured.";
    else if (fileName.includes("mountain")) description = "A stunning mountain landscape.";
    else if (fileName.includes("cat")) description = "A playful cat lounging.";
    else if (fileName.includes("forest")) description = "A dense green forest.";
    else if (fileName.includes("mouse")) description = "A mouse.";
    else if (fileName.includes("spiderman")) description = "Spiderman.";
    else if (fileName.includes("city")) description = "A bustling cityscape.";
    else if (fileName.includes("sunset")) description = "A breathtaking sunset view.";
    else if (fileName.includes("river")) description = "A serene river flowing.";
    else if (fileName.includes("car")) description = "A stylish car on display.";
    else if (fileName.includes("bike")) description = "A cool motorbike in action.";
    else if (fileName.includes("flower")) description = "A close-up of a vibrant flower.";
    else if (fileName.includes("bird")) description = "A colorful bird perched.";
    else if (fileName.includes("bridge")) description = "A majestic bridge crossing.";
    else if (fileName.includes("snow")) description = "A snowy winter landscape.";
    else if (fileName.includes("rain")) description = "A rainy street scene.";
    else if (fileName.includes("desert")) description = "A vast desert landscape.";
    else if (fileName.includes("castle")) description = "An ancient castle towering.";
    else if (fileName.includes("lake")) description = "A calm lake at dawn.";
    else if (fileName.includes("island")) description = "A tropical island paradise.";
    else if (fileName.includes("statue")) description = "A famous statue monument.";
    else if (fileName.includes("fireworks")) description = "Fireworks lighting the sky.";
    else if (fileName.includes("street")) description = "A lively street market.";
    else if (fileName.includes("train")) description = "A fast-moving train.";
    else if (fileName.includes("temple")) description = "A traditional temple structure.";
    else if (fileName.includes("garden")) description = "A peaceful garden view.";
    else if (fileName.includes("fish")) description = "A colorful fish underwater.";
    else if (fileName.includes("food")) description = "A delicious meal served.";
    else if (fileName.includes("skyline")) description = "A city's skyline at dusk.";
    else if (fileName.includes("airplane")) description = "An airplane soaring above.";
    else if (fileName.includes("boat")) description = "A boat sailing the sea.";
    else if (fileName.includes("market")) description = "A busy marketplace scene.";
    else if (fileName.includes("library")) description = "A cozy library room.";
    else if (fileName.includes("museum")) description = "An interior of a museum.";
    else if (fileName.includes("volcano")) description = "A volcano erupting.";
    else if (fileName.includes("canyon")) description = "A deep rocky canyon.";
    else if (fileName.includes("valley")) description = "A green valley between hills.";
    else if (fileName.includes("sunrise")) description = "A peaceful sunrise scene.";
    else if (fileName.includes("orchard")) description = "A blossoming orchard.";
    else if (fileName.includes("festival")) description = "A colorful festival celebration.";
    else if (fileName.includes("temple")) description = "A sacred temple complex.";
    else if (fileName.includes("monument")) description = "A grand historical monument.";
    else if (fileName.includes("giraffe")) description = "A tall giraffe in the wild.";
    else if (fileName.includes("elephant")) description = "A majestic elephant walking.";
    else if (fileName.includes("lion")) description = "A fierce lion roaring.";
    else if (fileName.includes("tiger")) description = "A majestic tiger prowling.";
    else if (fileName.includes("panda")) description = "A cute panda eating bamboo.";
    else if (fileName.includes("koala")) description = "A sleepy koala on a tree.";
    else if (fileName.includes("butterfly")) description = "A delicate butterfly resting.";
    else if (fileName.includes("horse")) description = "A galloping horse.";
    else if (fileName.includes("dolphin")) description = "A playful dolphin leaping.";
    else if (fileName.includes("whale")) description = "A massive whale in the ocean.";
    else if (fileName.includes("shark")) description = "A fierce shark underwater.";
    else if (fileName.includes("crab")) description = "A crab scuttling on the shore.";
    else if (fileName.includes("zebra")) description = "A zebra grazing on the plains.";
    else if (fileName.includes("parrot")) description = "A colorful parrot squawking.";
    else if (fileName.includes("peacock")) description = "A peacock displaying feathers.";
    else if (fileName.includes("cherry")) description = "Cherry blossoms blooming.";
    else if (fileName.includes("rainbow")) description = "A bright rainbow in the sky.";
    else if (fileName.includes("rocket")) description = "A rocket launching.";
    else if (fileName.includes("planet")) description = "A distant planet in space.";
    else if (fileName.includes("moon")) description = "A full moon shining.";
    else if (fileName.includes("stars")) description = "A starry night sky.";
    else if (fileName.includes("space")) description = "Outer space scenery.";
    else if (fileName.includes("aurora")) description = "The northern lights glowing.";
    else if (fileName.includes("cave")) description = "A mysterious cave entrance.";
    else if (fileName.includes("cliff")) description = "A steep rocky cliff.";
    else if (fileName.includes("waterfall")) description = "A powerful waterfall cascade.";
    else if (fileName.includes("trainstation")) description = "A bustling train station.";
    else if (fileName.includes("campfire")) description = "A cozy campfire at night.";
    else if (fileName.includes("hiking")) description = "Hikers on a mountain trail.";
    else if (fileName.includes("surfing")) description = "A surfer riding a wave.";
    else if (fileName.includes("skiing")) description = "Skiers descending snowy slopes.";
    else if (fileName.includes("balloon")) description = "Hot air balloons floating.";
    else if (fileName.includes("farm")) description = "A scenic countryside farm.";
    else if (fileName.includes("village")) description = "A peaceful village setting.";
    else if (fileName.includes("tower")) description = "A tall tower reaching the sky.";
    else if (fileName.includes("harbor")) description = "A harbor with anchored boats.";
    else if (fileName.includes("metro")) description = "A busy metro station.";
    else if (fileName.includes("subway")) description = "A subway train arriving.";
    else if (fileName.includes("restaurant")) description = "A cozy restaurant interior.";
    else if (fileName.includes("cafe")) description = "A small charming cafe.";
    else if (fileName.includes("bakery")) description = "A bakery filled with pastries.";
    else if (fileName.includes("statueofliberty")) description = "The Statue of Liberty.";
    else if (fileName.includes("eiffel")) description = "The Eiffel Tower in Paris.";
    else if (fileName.includes("colosseum")) description = "The Roman Colosseum.";
    else if (fileName.includes("pyramid")) description = "The pyramids of Egypt.";
    else if (fileName.includes("greatwall")) description = "The Great Wall of China.";
    else if (fileName.includes("bigben")) description = "Big Ben in London.";
    else if (fileName.includes("machupicchu")) description = "Machu Picchu ruins.";
    else if (fileName.includes("opera")) description = "Sydney Opera House.";
    else if (fileName.includes("hollywood")) description = "Hollywood sign in Los Angeles.";
    else if (fileName.includes("mountfuji")) description = "Mount Fuji in Japan.";
    else if (fileName.includes("niagarafalls")) description = "Niagara Falls cascading.";
    else if (fileName.includes("amazon")) description = "Amazon rainforest scenery.";
    else if (fileName.includes("grandcanyon")) description = "The Grand Canyon view.";
    else if (fileName.includes("safari")) description = "A thrilling safari ride.";
    else if (fileName.includes("racecar")) description = "A high-speed race car.";
    else if (fileName.includes("yacht")) description = "A luxury yacht cruising.";
    else if (fileName.includes("iceberg")) description = "A giant iceberg floating.";
    else if (fileName.includes("glacier")) description = "A frozen glacier landscape.";
    else if (fileName.includes("waterfall")) description = "A powerful waterfall cascading.";
    else if (fileName.includes("waterfall")) description = "A powerful waterfall cascading.";
else if (fileName.includes("trainstation")) description = "A bustling train station.";
else if (fileName.includes("campfire")) description = "A cozy campfire at night.";
else if (fileName.includes("hiking")) description = "Hikers on a mountain trail.";
else if (fileName.includes("surfing")) description = "A surfer riding a wave.";
else if (fileName.includes("skiing")) description = "Skiers descending snowy slopes.";
else if (fileName.includes("balloon")) description = "Hot air balloons floating.";
else if (fileName.includes("farm")) description = "A scenic countryside farm.";
else if (fileName.includes("village")) description = "A peaceful village setting.";
else if (fileName.includes("tower")) description = "A tall tower reaching the sky.";
else if (fileName.includes("harbor")) description = "A harbor with anchored boats.";
else if (fileName.includes("metro")) description = "A busy metro station.";
else if (fileName.includes("subway")) description = "A subway train arriving.";
else if (fileName.includes("restaurant")) description = "A cozy restaurant interior.";
else if (fileName.includes("cafe")) description = "A small charming cafe.";
else if (fileName.includes("bakery")) description = "A bakery filled with pastries.";
else if (fileName.includes("statueofliberty")) description = "The Statue of Liberty.";
else if (fileName.includes("eiffel")) description = "The Eiffel Tower in Paris.";
else if (fileName.includes("colosseum")) description = "The Roman Colosseum.";
else if (fileName.includes("pyramid")) description = "The pyramids of Egypt.";
else if (fileName.includes("greatwall")) description = "The Great Wall of China.";
else if (fileName.includes("bigben")) description = "Big Ben in London.";
else if (fileName.includes("machupicchu")) description = "Machu Picchu ruins.";
else if (fileName.includes("opera")) description = "Sydney Opera House.";
else if (fileName.includes("hollywood")) description = "Hollywood sign in Los Angeles.";
else if (fileName.includes("mountfuji")) description = "Mount Fuji in Japan.";
else if (fileName.includes("niagarafalls")) description = "Niagara Falls cascading.";
else if (fileName.includes("amazon")) description = "Amazon rainforest scenery.";
else if (fileName.includes("grandcanyon")) description = "The Grand Canyon view.";
else if (fileName.includes("safari")) description = "A thrilling safari ride.";
else if (fileName.includes("racecar")) description = "A high-speed race car.";
else if (fileName.includes("yacht")) description = "A luxury yacht cruising.";
else if (fileName.includes("iceberg")) description = "A giant iceberg floating.";
else if (fileName.includes("glacier")) description = "A frozen glacier landscape.";
else if (fileName.includes("volcano")) description = "A volcano erupting with lava.";
else if (fileName.includes("canyon")) description = "A deep rocky canyon.";
else if (fileName.includes("valley")) description = "A green valley between hills.";
else if (fileName.includes("sunrise")) description = "A peaceful sunrise scene.";
else if (fileName.includes("orchard")) description = "A blossoming orchard with trees.";
else if (fileName.includes("festival")) description = "A colorful festival celebration.";
else if (fileName.includes("temple")) description = "A sacred temple complex.";
else if (fileName.includes("monument")) description = "A grand historical monument.";
else if (fileName.includes("giraffe")) description = "A tall giraffe in the wild.";
else if (fileName.includes("elephant")) description = "A majestic elephant walking.";
else if (fileName.includes("lion")) description = "A fierce lion roaring.";
else if (fileName.includes("tiger")) description = "A majestic tiger prowling.";
else if (fileName.includes("panda")) description = "A cute panda eating bamboo.";
else if (fileName.includes("koala")) description = "A sleepy koala on a tree.";
else if (fileName.includes("butterfly")) description = "A delicate butterfly resting on a flower.";
else if (fileName.includes("horse")) description = "A galloping horse running through the field.";
else if (fileName.includes("dolphin")) description = "A playful dolphin leaping out of the water.";
else if (fileName.includes("whale")) description = "A massive whale swimming through the ocean.";
else if (fileName.includes("shark")) description = "A fierce shark hunting underwater.";
else if (fileName.includes("crab")) description = "A crab scuttling on the shore.";
else if (fileName.includes("zebra")) description = "A zebra grazing on the plains.";
else if (fileName.includes("parrot")) description = "A colorful parrot squawking in the trees.";
else if (fileName.includes("peacock")) description = "A peacock displaying its beautiful feathers.";
else if (fileName.includes("cherry")) description = "Cherry blossoms blooming in spring.";
else if (fileName.includes("rainbow")) description = "A bright rainbow appearing after rain.";
else if (fileName.includes("rocket")) description = "A rocket blasting off into space.";
else if (fileName.includes("planet")) description = "A distant planet orbiting a star.";
else if (fileName.includes("moon")) description = "A full moon shining brightly in the night sky.";
else if (fileName.includes("stars")) description = "A starry night sky filled with twinkling stars.";
else if (fileName.includes("space")) description = "Outer space with a view of distant galaxies.";
else if (fileName.includes("aurora")) description = "The northern lights glowing in the sky.";
else if (fileName.includes("cave")) description = "A mysterious cave entrance waiting to be explored.";
else if (fileName.includes("cliff")) description = "A steep rocky cliff overlooking the ocean.";
else if (fileName.includes("waterfall")) description = "A stunning waterfall cascading over rocks.";
else if (fileName.includes("trainstation")) description = "A busy train station with passengers.";
else if (fileName.includes("campfire")) description = "A cozy campfire crackling under the stars.";
else if (fileName.includes("hiking")) description = "A group of hikers trekking up a mountain.";
else if (fileName.includes("surfing")) description = "A surfer catching a big wave in the ocean.";
else if (fileName.includes("skiing")) description = "Skiers racing down snowy mountain slopes.";
else if (fileName.includes("balloon")) description = "Colorful hot air balloons floating in the sky.";
else if (fileName.includes("farm")) description = "A peaceful farm with livestock grazing.";
else if (fileName.includes("village")) description = "A small village nestled in the hills.";
else if (fileName.includes("tower")) description = "A historic clock tower in a city square.";
else if (fileName.includes("harbor")) description = "A calm harbor with boats anchored in the water.";
else if (fileName.includes("metro")) description = "A metro station bustling with commuters.";
else if (fileName.includes("subway")) description = "A subway train entering a dark tunnel.";
else if (fileName.includes("restaurant")) description = "A chic restaurant with elegant decor.";
else if (fileName.includes("cafe")) description = "A charming cafe with warm lighting.";
else if (fileName.includes("bakery")) description = "A bakery with fresh bread and pastries.";
else if (fileName.includes("statueofliberty")) description = "The Statue of Liberty standing tall.";
else if (fileName.includes("eiffel")) description = "The Eiffel Tower lit up at night.";
else if (fileName.includes("colosseum")) description = "The Colosseum in Rome, Italy, with ancient ruins.";
else if (fileName.includes("pyramid")) description = "The pyramids of Egypt towering in the desert.";
else if (fileName.includes("greatwall")) description = "The Great Wall of China winding over mountains.";
else if (fileName.includes("bigben")) description = "Big Ben at sunset in London.";
else if (fileName.includes("sunset")) description = "A breathtaking sunset over the horizon.";
else if (fileName.includes("beach")) description = "A serene beach with soft golden sand.";
else if (fileName.includes("mountain")) description = "Snow-capped mountains in the distance.";
else if (fileName.includes("ocean")) description = "The vast ocean stretching to the horizon.";
else if (fileName.includes("forest")) description = "A lush green forest with towering trees.";
else if (fileName.includes("desert")) description = "A vast desert with rolling sand dunes.";
else if (fileName.includes("cityscape")) description = "A vibrant city skyline at night.";
else if (fileName.includes("street")) description = "A busy street filled with people and cars.";
else if (fileName.includes("nightlife")) description = "The exciting nightlife of a busy city.";
else if (fileName.includes("skyline")) description = "The glowing skyline of a bustling metropolis.";
else if (fileName.includes("bridge")) description = "A majestic bridge crossing over a river.";
else if (fileName.includes("lake")) description = "A calm lake with a mountain backdrop.";
else if (fileName.includes("snow")) description = "Snowflakes gently falling on the ground.";
else if (fileName.includes("starry")) description = "A starry sky with a few visible constellations.";
else if (fileName.includes("night")) description = "A quiet night with the moon shining brightly.";
else if (fileName.includes("clouds")) description = "Fluffy clouds floating across the sky.";
else if (fileName.includes("rain")) description = "Gentle rain falling on a window.";
else if (fileName.includes("storm")) description = "A thunderstorm with dark clouds and lightning.";
else if (fileName.includes("wind")) description = "Wind blowing through the trees on a cool day.";
else if (fileName.includes("autumn")) description = "Autumn leaves falling from the trees.";
else if (fileName.includes("spring")) description = "Vibrant spring flowers blooming in the garden.";
else if (fileName.includes("summer")) description = "A hot summer day with people enjoying the beach.";
else if (fileName.includes("winter")) description = "A peaceful winter scene with snow-covered trees.";
else if (fileName.includes("lighthouse")) description = "A lighthouse standing tall near the ocean.";
else if (fileName.includes("water")) description = "Clear water flowing through a river.";
else if (fileName.includes("waterfall")) description = "A majestic waterfall cascading over rocks.";
else if (fileName.includes("mountainrange")) description = "A mountain range covered in snow.";
else if (fileName.includes("canyon")) description = "A grand canyon with steep cliffs.";
else if (fileName.includes("cave")) description = "A dark cave with stalactites and stalagmites.";
else if (fileName.includes("cliffs")) description = "Steep cliffs overlooking the sea.";
else if (fileName.includes("valley")) description = "A green valley between two mountains.";
else if (fileName.includes("desertdune")) description = "A large sand dune in the middle of the desert.";
else if (fileName.includes("island")) description = "A small island surrounded by blue water.";
else if (fileName.includes("tropical")) description = "A tropical island with lush greenery and clear blue waters.";
else if (fileName.includes("rainforest")) description = "A dense rainforest filled with diverse wildlife.";
else if (fileName.includes("volcano")) description = "An erupting volcano spewing lava into the air.";
else if (fileName.includes("wildlife")) description = "A variety of wildlife living in their natural habitat.";
else if (fileName.includes("jungle")) description = "A dense jungle full of exotic animals.";
else if (fileName.includes("zoo")) description = "A zoo with various animals in enclosures.";
else if (fileName.includes("aquarium")) description = "An aquarium with colorful fish swimming in tanks.";
else if (fileName.includes("coral")) description = "Vibrant coral reefs teeming with marine life.";
else if (fileName.includes("sharks")) description = "A group of sharks swimming in the ocean.";
else if (fileName.includes("whales")) description = "A pod of whales swimming gracefully.";
else if (fileName.includes("dolphins")) description = "Dolphins leaping out of the ocean.";
else if (fileName.includes("penguin")) description = "A penguin waddling on the ice.";
else if (fileName.includes("tiger")) description = "A tiger prowling through the forest.";
else if (fileName.includes("elephant")) description = "An elephant walking through the savannah.";
else if (fileName.includes("giraffe")) description = "A giraffe grazing on treetops.";
else if (fileName.includes("lion")) description = "A fierce lion resting in the grass.";
else if (fileName.includes("bear")) description = "A bear fishing in a river.";
else if (fileName.includes("koala")) description = "A koala sleeping in a tree.";
else if (fileName.includes("panda")) description = "A panda munching on bamboo.";
else if (fileName.includes("wolf")) description = "A lone wolf howling at the moon.";
else if (fileName.includes("fox")) description = "A fox running through the woods.";
else if (fileName.includes("squirrel")) description = "A squirrel collecting acorns in the forest.";
else if (fileName.includes("rabbit")) description = "A rabbit hopping through the grass.";
else if (fileName.includes("bird")) description = "A bird flying across the blue sky.";
else if (fileName.includes("butterfly")) description = "A butterfly fluttering among flowers.";
else if (fileName.includes("bees")) description = "Bees buzzing around blooming flowers.";
else if (fileName.includes("beachball")) description = "A colorful beach ball bouncing on the sand.";
else if (fileName.includes("campfire")) description = "A campfire crackling under the night sky.";
else if (fileName.includes("fishing")) description = "A fisherman casting his line into a river.";
else if (fileName.includes("hiking")) description = "Hikers walking along a mountain trail.";
else if (fileName.includes("cycling")) description = "A cyclist riding through a scenic path.";
else if (fileName.includes("surfing")) description = "A surfer riding a huge wave.";
else if (fileName.includes("skiing")) description = "Skiers descending a snowy mountain slope.";
else if (fileName.includes("snowboard")) description = "A snowboarder carving through the snow.";
else if (fileName.includes("climbing")) description = "A climber scaling a steep rock face.";
else if (fileName.includes("hotairballoon")) description = "Hot air balloons floating in the sky.";
else if (fileName.includes("racecar")) description = "A sleek racecar speeding on the track.";
else if (fileName.includes("yacht")) description = "A luxurious yacht sailing through the ocean.";
else if (fileName.includes("boat")) description = "A small boat drifting on a calm lake.";
else if (fileName.includes("jetplane")) description = "A jetplane soaring through the sky.";
else if (fileName.includes("helicopter")) description = "A helicopter hovering above a city.";
else if (fileName.includes("rocket")) description = "A rocket launching into space.";
else if (fileName.includes("astronaut")) description = "An astronaut floating in space.";
else if (fileName.includes("satellite")) description = "A satellite orbiting Earth.";
else if (fileName.includes("moon")) description = "The moon shining brightly in the night sky.";
else if (fileName.includes("stars")) description = "A starry sky twinkling in the distance.";
else if (fileName.includes("comet")) description = "A comet streaking across the sky.";
else if (fileName.includes("planet")) description = "A distant planet surrounded by rings.";
else if (fileName.includes("galaxy")) description = "A swirling galaxy filled with stars.";
else if (fileName.includes("asteroid")) description = "A large asteroid hurtling through space.";
else if (fileName.includes("mars")) description = "The red planet Mars, visible from space.";
else if (fileName.includes("earth")) description = "Earth as seen from space, with oceans and landmasses.";
else if (fileName.includes("saturn")) description = "Saturn with its iconic rings.";
else if (fileName.includes("venus")) description = "The planet Venus glowing brightly in the night sky.";
else if (fileName.includes("jupiter")) description = "The gas giant Jupiter, with its massive storm.";
else if (fileName.includes("neptune")) description = "Neptune, the farthest planet from the sun.";
else if (fileName.includes("milkyway")) description = "The Milky Way galaxy, filled with stars.";
else if (fileName.includes("aurora")) description = "The northern lights lighting up the night sky.";
else if (fileName.includes("sun")) description = "A brilliant sunrise over the horizon.";
else if (fileName.includes("sunflower")) description = "A field of tall sunflowers swaying in the breeze.";
else if (fileName.includes("orchid")) description = "A delicate orchid blooming in the sunlight.";
else if (fileName.includes("rose")) description = "A vibrant rose in full bloom.";
else if (fileName.includes("tulip")) description = "A colorful tulip standing tall in the garden.";
else if (fileName.includes("lily")) description = "A lily flower blooming gracefully.";
else if (fileName.includes("daffodil")) description = "A patch of bright yellow daffodils.";
else if (fileName.includes("cactus")) description = "A cactus standing tall in the desert.";
else if (fileName.includes("palm")) description = "A palm tree swaying in the tropical breeze.";
else if (fileName.includes("maple")) description = "A maple tree with vibrant fall leaves.";
else if (fileName.includes("pine")) description = "A tall pine tree in a dense forest.";
else if (fileName.includes("oak")) description = "A strong oak tree in the park.";
else if (fileName.includes("willow")) description = "A willow tree with cascading branches.";
else if (fileName.includes("birch")) description = "A birch tree with white bark.";
else if (fileName.includes("flower")) description = "A cluster of colorful flowers in bloom.";
else if (fileName.includes("vine")) description = "A vine climbing up a trellis.";
else if (fileName.includes("garden")) description = "A well-kept garden with a variety of plants.";
else if (fileName.includes("backyard")) description = "A peaceful backyard with a hammock.";
else if (fileName.includes("pond")) description = "A calm pond surrounded by greenery.";
else if (fileName.includes("lakeview")) description = "A stunning view of a tranquil lake.";
else if (fileName.includes("gardenpath")) description = "A stone path winding through a beautiful garden.";
else if (fileName.includes("greenhouse")) description = "A greenhouse filled with plants and flowers.";
else if (fileName.includes("patio")) description = "A cozy patio with a view of the garden.";
else if (fileName.includes("balcony")) description = "A balcony overlooking a busy street.";
else if (fileName.includes("terrace")) description = "A rooftop terrace with panoramic views.";
else if (fileName.includes("pavilion")) description = "A pavilion in the park with benches.";
else if (fileName.includes("fountain")) description = "A beautiful fountain in a garden.";
else if (fileName.includes("person")) description = "A person standing confidently.";
else if (fileName.includes("portrait")) description = "A close-up portrait of a person smiling.";
else if (fileName.includes("family")) description = "A happy family posing together.";
else if (fileName.includes("couple")) description = "A couple smiling at each other.";
else if (fileName.includes("friendship")) description = "Two friends laughing together.";
else if (fileName.includes("woman")) description = "A woman smiling in a casual setting.";
else if (fileName.includes("man")) description = "A man standing tall in a formal outfit.";
else if (fileName.includes("child")) description = "A child playing in the park.";
else if (fileName.includes("elderly")) description = "An elderly person sitting on a bench, smiling.";
else if (fileName.includes("runner")) description = "A person jogging through a city street.";
else if (fileName.includes("yoga")) description = "A person practicing yoga on a mat.";
else if (fileName.includes("dancer")) description = "A dancer performing on stage.";
else if (fileName.includes("chef")) description = "A chef preparing food in a kitchen.";
else if (fileName.includes("doctor")) description = "A doctor talking to a patient in an office.";
else if (fileName.includes("teacher")) description = "A teacher explaining a lesson to students.";
else if (fileName.includes("artist")) description = "An artist painting on a canvas.";
else if (fileName.includes("photographer")) description = "A photographer taking pictures outdoors.";
else if (fileName.includes("gardener")) description = "A gardener planting flowers in a garden.";
else if (fileName.includes("traveler")) description = "A traveler with a backpack walking on a trail.";
else if (fileName.includes("businessman")) description = "A businessman walking in a corporate setting.";
else if (fileName.includes("scientist")) description = "A scientist working with lab equipment.";
else if (fileName.includes("constructionworker")) description = "A construction worker wearing a hard hat.";
else if (fileName.includes("fisherman")) description = "A fisherman casting his net into a river.";
else if (fileName.includes("biker")) description = "A person riding a bicycle on a road.";
else if (fileName.includes("mountaineer")) description = "A mountaineer climbing a steep rock face.";
else if (fileName.includes("hiker")) description = "A person hiking along a mountain trail.";
else if (fileName.includes("swimmer")) description = "A swimmer diving into a pool.";
else if (fileName.includes("snowboarder")) description = "A snowboarder sliding down a snow-covered hill.";
else if (fileName.includes("skier")) description = "A skier descending a mountain slope.";
else if (fileName.includes("skater")) description = "A skater performing tricks at a skate park.";
else if (fileName.includes("surfer")) description = "A surfer riding a wave in the ocean.";
else if (fileName.includes("cyclist")) description = "A cyclist riding on a paved road.";
else if (fileName.includes("ballerina")) description = "A ballerina performing an elegant pirouette.";
else if (fileName.includes("guitarist")) description = "A guitarist playing an acoustic guitar.";
else if (fileName.includes("photography")) description = "A photographer capturing a scenic view.";
else if (fileName.includes("painter")) description = "A painter working on a large canvas.";
else if (fileName.includes("sculptor")) description = "A sculptor chiseling a statue from marble.";
else if (fileName.includes("businesswoman")) description = "A businesswoman working at her desk.";
else if (fileName.includes("salesperson")) description = "A salesperson assisting a customer in a store.";
else if (fileName.includes("entrepreneur")) description = "An entrepreneur presenting an idea to a team.";
else if (fileName.includes("mountainview")) description = "A person standing on a mountain, gazing at the horizon.";
else if (fileName.includes("beachview")) description = "A person enjoying the view of the ocean from a beach.";
else if (fileName.includes("waterfallview")) description = "A person standing near a waterfall, admiring the view.";
else if (fileName.includes("sunsetview")) description = "A person watching the sunset by the sea.";
else if (fileName.includes("cityview")) description = "A person standing on a balcony with a city skyline view.";
else if (fileName.includes("streetview")) description = "A person walking down a busy street.";
else if (fileName.includes("park")) description = "A person walking in a green park with trees.";
else if (fileName.includes("flowerfield")) description = "A person walking through a colorful flower field.";
else if (fileName.includes("gardenpath")) description = "A person walking down a garden path surrounded by flowers.";
else if (fileName.includes("mountainpath")) description = "A person walking along a rocky mountain path.";
else if (fileName.includes("desertpath")) description = "A person walking on a sandy desert trail.";
else if (fileName.includes("beachwalk")) description = "A person walking barefoot along a beach.";
else if (fileName.includes("flowergarden")) description = "A person strolling through a blooming flower garden.";
else if (fileName.includes("waterfront")) description = "A person standing by the water's edge, looking out.";
else if (fileName.includes("fieldofflowers")) description = "A person lying on the grass in a field of flowers.";
else if (fileName.includes("botanicalgarden")) description = "A person exploring a botanical garden.";
else if (fileName.includes("cliffside")) description = "A person standing on the edge of a cliff.";
else if (fileName.includes("snowyroad")) description = "A person walking along a snow-covered road.";
else if (fileName.includes("parkbench")) description = "A person sitting on a park bench, enjoying the view.";
else if (fileName.includes("bench")) description = "A person sitting on a bench in a quiet park.";
else if (fileName.includes("tree")) description = "A person sitting under the shade of a tree.";
else if (fileName.includes("sunflowerfield")) description = "A person standing in a field of sunflowers.";
else if (fileName.includes("springflowers")) description = "A person enjoying the beauty of spring flowers.";
else if (fileName.includes("fallleaves")) description = "A person walking through a forest with fall-colored leaves.";
else if (fileName.includes("flowerbouquet")) description = "A person holding a bouquet of flowers in their hands.";
else if (fileName.includes("mountainridge")) description = "A person standing on a mountain ridge, looking out.";
else if (fileName.includes("desertdunes")) description = "A person walking across sand dunes in the desert.";
else if (fileName.includes("waterfalltrail")) description = "A person hiking along a trail leading to a waterfall.";
else if (fileName.includes("canyontrail")) description = "A person walking through a narrow canyon.";
else if (fileName.includes("citystreet")) description = "A person walking down a city street with tall buildings.";
else if (fileName.includes("trainstation")) description = "A person waiting for a train at a station.";
else if (fileName.includes("airport")) description = "A person walking through an airport terminal.";
else if (fileName.includes("marketplace")) description = "A person shopping in a local marketplace.";
else if (fileName.includes("museum")) description = "A person admiring art at a museum.";
else if (fileName.includes("restaurant")) description = "A person dining in a cozy restaurant.";
else if (fileName.includes("gallery")) description = "A person viewing artwork at an art gallery.";
else if (fileName.includes("streetmarket")) description = "A person browsing at a busy street market.";
else if (fileName.includes("coffeehouse")) description = "A person sipping coffee at a quiet coffeehouse.";
else if (fileName.includes("library")) description = "A person reading a book in a quiet library.";
else if (fileName.includes("beachhut")) description = "A person relaxing inside a beach hut.";
else if (fileName.includes("cottage")) description = "A person relaxing on the porch of a cottage.";
else if (fileName.includes("farmhouse")) description = "A person standing outside a farmhouse.";
else if (fileName.includes("vineyard")) description = "A person walking through a lush vineyard.";
else if (fileName.includes("poolside")) description = "A person lounging by a poolside.";
else if (fileName.includes("mountainresort")) description = "A person relaxing at a mountain resort.";
else if (fileName.includes("skiresort")) description = "A person skiing on fresh snow at a resort.";
else if (fileName.includes("desertresort")) description = "A person lounging at a desert resort.";
else if (fileName.includes("beachresort")) description = "A person relaxing at a beach resort.";
else if (fileName.includes("jungle")) description = "A person exploring a dense jungle path.";
else if (fileName.includes("lakeview")) description = "A person sitting by a tranquil lake, enjoying the view.";
else if (fileName.includes("beachview")) description = "A person looking out at the beach from a balcony.";
else if (fileName.includes("cityview")) description = "A person overlooking the city from a rooftop.";
else if (fileName.includes("forestpath")) description = "A person walking through a shaded forest path.";
else if (fileName.includes("desertview")) description = "A person standing at the edge of a desert, gazing at the horizon.";
else if (fileName.includes("mountainview")) description = "A person enjoying the breathtaking view from a mountaintop.";
else if (fileName.includes("manwithdog")) description = "A man walking his dog in the park.";
else if (fileName.includes("womanwithdog")) description = "A woman playing with her dog in the backyard.";
else if (fileName.includes("girlwithcat")) description = "A girl sitting with her cat on a couch.";
else if (fileName.includes("manwithcat")) description = "A man petting his cat at home.";
else if (fileName.includes("motherwithchild")) description = "A mother holding her child in a park.";
else if (fileName.includes("fatherwithchild")) description = "A father teaching his child how to ride a bike.";
else if (fileName.includes("baby")) description = "A baby smiling while lying on a blanket.";
else if (fileName.includes("toddler")) description = "A toddler playing with toys on the floor.";
else if (fileName.includes("childwithball")) description = "A child kicking a soccer ball in the yard.";
else if (fileName.includes("personwithumbrella")) description = "A person holding an umbrella in the rain.";
else if (fileName.includes("persononbeach")) description = "A person walking along the beach at sunset.";
else if (fileName.includes("personinpark")) description = "A person jogging through a park surrounded by trees.";
else if (fileName.includes("personinforest")) description = "A person walking through a dense forest trail.";
else if (fileName.includes("personinmountains")) description = "A person standing on a mountain ridge, gazing at the view.";
else if (fileName.includes("personinthecity")) description = "A person walking down a busy city street.";
else if (fileName.includes("persononrooftop")) description = "A person looking out over the city from a rooftop.";
else if (fileName.includes("personbywater")) description = "A person standing by a serene lake.";
else if (fileName.includes("personbywaterfall")) description = "A person standing near a waterfall, marveling at its beauty.";
else if (fileName.includes("personontrail")) description = "A person hiking along a scenic trail in the mountains.";
else if (fileName.includes("personbyriver")) description = "A person sitting on the bank of a flowing river.";
else if (fileName.includes("personinparkbench")) description = "A person sitting on a park bench, reading a book.";
else if (fileName.includes("personbytree")) description = "A person leaning against a large tree in a forest.";
else if (fileName.includes("personwithflowers")) description = "A person holding a bouquet of colorful flowers.";
else if (fileName.includes("personwithbackpack")) description = "A person walking with a backpack on a hiking trail.";
else if (fileName.includes("personwithhat")) description = "A person wearing a wide-brimmed hat on a sunny day.";
else if (fileName.includes("persononmountain")) description = "A person standing triumphantly on top of a mountain.";
else if (fileName.includes("personbycliff")) description = "A person standing at the edge of a cliff, gazing at the horizon.";
else if (fileName.includes("persononbeachrocks")) description = "A person standing on rocks by the ocean, watching the waves crash.";
else if (fileName.includes("personinwinter")) description = "A person wearing a winter coat walking through a snowy landscape.";
else if (fileName.includes("personwithsnow")) description = "A person playing in the snow with a snowball.";
else if (fileName.includes("personinrain")) description = "A person walking in the rain with a raincoat.";
else if (fileName.includes("personwithglasses")) description = "A person wearing stylish glasses and a smile.";
else if (fileName.includes("persononbike")) description = "A person riding a bicycle on a scenic path.";
else if (fileName.includes("personwithchildrenscooter")) description = "A person helping a child with a scooter.";
else if (fileName.includes("personinforestpath")) description = "A person walking along a narrow forest path.";
else if (fileName.includes("personinfield")) description = "A person standing in a field of tall grass.";
else if (fileName.includes("personinboating")) description = "A person rowing a boat across a calm lake.";
else if (fileName.includes("personwithcoffee")) description = "A person enjoying a cup of coffee in a cozy cafe.";
else if (fileName.includes("personwithlaptop")) description = "A person working on a laptop at a coffee shop.";
else if (fileName.includes("personwithdogpark")) description = "A person playing fetch with their dog in a park.";
else if (fileName.includes("persononbenchpark")) description = "A person sitting on a park bench, people-watching.";
else if (fileName.includes("persononstaircase")) description = "A person walking up an ornate staircase.";
else if (fileName.includes("personwalkinginthecity")) description = "A person strolling through a lively city square.";
else if (fileName.includes("personontreetop")) description = "A person standing on a platform high in the trees.";
else if (fileName.includes("personwithsunnybackground")) description = "A person enjoying a sunny day outdoors.";
else if (fileName.includes("personinreflection")) description = "A person admiring their reflection in a calm pond.";
else if (fileName.includes("personintrees")) description = "A person standing among tall trees in a forest.";
else if (fileName.includes("personinfieldofwheat")) description = "A person walking through a golden wheat field.";
else if (fileName.includes("personondeserttrail")) description = "A person walking along a dirt trail in the desert.";
else if (fileName.includes("personwithmountainbackground")) description = "A person standing in front of a towering mountain.";
else if (fileName.includes("personwithbeachbackground")) description = "A person enjoying a beautiful beach sunset.";
else if (fileName.includes("personbycampsite")) description = "A person sitting by a campfire at a campsite.";
else if (fileName.includes("personwithlakeview")) description = "A person relaxing on a dock with a lake view.";
else if (fileName.includes("persononrooftopview")) description = "A person enjoying the view from a city rooftop.";
else if (fileName.includes("personwithforestbackground")) description = "A person standing against a forest backdrop.";
else if (fileName.includes("personwithmountainview")) description = "A person overlooking a mountain range from a high vantage point.";
else if (fileName.includes("personinhighaltitude")) description = "A person standing at high altitude, with clouds beneath them.";
else if (fileName.includes("persononhikingtrail")) description = "A person hiking along a mountain trail with scenic views.";
else if (fileName.includes("personbycampfire")) description = "A person sitting by a campfire at night.";
else if (fileName.includes("personinbackyard")) description = "A person relaxing in their backyard, enjoying the outdoors.";
else if (fileName.includes("personinthealps")) description = "A person skiing in the snow-covered Alps.";
else if (fileName.includes("personinclouds")) description = "A person walking on a cloud-covered mountain peak.";
else if (fileName.includes("personbywaterhole")) description = "A person standing by a waterhole in the wilderness.";
else if (fileName.includes("personinsunset")) description = "A person silhouetted against a colorful sunset sky.";
else if (fileName.includes("persononbeachwaves")) description = "A person wading through gentle waves at the beach.";
else if (fileName.includes("personinhotairballoon")) description = "A person flying in a hot air balloon above the countryside.";
else if (fileName.includes("personwithdesertbackground")) description = "A person standing in front of vast desert dunes.";
else if (fileName.includes("personwithclouds")) description = "A person standing beneath a sky filled with clouds.";
else if (fileName.includes("personbygardenfountain")) description = "A person admiring a garden fountain.";
else if (fileName.includes("persononriverbank")) description = "A person sitting by the river, with the water flowing gently.";
else if (fileName.includes("personwithwaterfallbackdrop")) description = "A person standing in front of a large waterfall.";
else if (fileName.includes("personbyvintagecar")) description = "A person leaning on a vintage car in an old street.";
else if (fileName.includes("persononcountryroad")) description = "A person walking down a peaceful country road.";
else if (fileName.includes("personontreetopplatform")) description = "A person standing on a tree-top observation platform.";
else if (fileName.includes("personwithmountaininbackground")) description = "A person standing with a mountain backdrop.";
else if (fileName.includes("personbydesertmountain")) description = "A person standing in front of a desert mountain landscape.";
else if (fileName.includes("personinplains")) description = "A person standing in the middle of a vast plain.";
else if (fileName.includes("personwithcountrysideview")) description = "A person looking over a peaceful countryside view.";
else if (fileName.includes("persononriverboat")) description = "A person riding a boat down a river in a lush landscape.";
else if (fileName.includes("persononhorseback")) description = "A person riding a horse through a field.";
else if (fileName.includes("personinbrightclothing")) description = "A person wearing bright clothing under the sun.";
else if (fileName.includes("persononbeachpier")) description = "A person standing at the edge of a beach pier.";
else if (fileName.includes("persononvacation")) description = "A person on vacation exploring an exotic destination.";
else if (fileName.includes("personbyswimmingpool")) description = "A person relaxing by the side of a swimming pool.";
else if (fileName.includes("personwithbird")) description = "A person holding a bird gently in their hand.";
else if (fileName.includes("persononcamel")) description = "A person riding a camel across the desert.";
else if (fileName.includes("personindowntown")) description = "A person walking through a bustling downtown area.";
else if (fileName.includes("personbyjetty")) description = "A person standing on a jetty, looking at the water.";
else if (fileName.includes("personbymountainlake")) description = "A person sitting by a clear mountain lake.";
else if (fileName.includes("personbycliffside")) description = "A person standing at the edge of a cliff, gazing out.";
else if (fileName.includes("personwithsnowfall")) description = "A person walking through a snowfall in a quiet street.";
else if (fileName.includes("personinjungle")) description = "A person trekking through a dense jungle.";
else if (fileName.includes("personontopofcliff")) description = "A person standing triumphantly on top of a cliff.";
else if (fileName.includes("personintower")) description = "A person looking out from a tall observation tower.";
else if (fileName.includes("persononbridge")) description = "A person crossing a bridge over a river.";
else if (fileName.includes("personwithsunsetbackground")) description = "A person silhouetted against the vibrant colors of a sunset.";
else if (fileName.includes("persononskateboard")) description = "A person riding a skateboard down a smooth sidewalk.";
else if (fileName.includes("personwithmountainbackground")) description = "A person posing in front of a majestic mountain range.";
else if (fileName.includes("personinwater")) description = "A person swimming in a clear blue ocean.";
else if (fileName.includes("personwithcatbackdrop")) description = "A person sitting on a sofa, with a cat resting on their lap.";
else if (fileName.includes("personwithmountainpeak")) description = "A person reaching the peak of a mountain.";
else if (fileName.includes("persononbeachpath")) description = "A person walking along a path leading to the beach.";
else if (fileName.includes("persononrooftopgarden")) description = "A person enjoying the view from a rooftop garden.";
else if (fileName.includes("personinwaterfall")) description = "A person standing under a waterfall, with water cascading around them.";
else if (fileName.includes("personinvintagecar")) description = "A person driving a vintage car down a scenic road.";
else if (fileName.includes("personincloud")) description = "A person standing among the clouds in the sky.";
else if (fileName.includes("persononhikingtrail")) description = "A person hiking along a dirt trail through the forest.";
else if (fileName.includes("personatnight")) description = "A person standing under a starry sky at night.";
else if (fileName.includes("personinfieldwithflowers")) description = "A person walking through a field filled with wildflowers.";
else if (fileName.includes("persononrockybeach")) description = "A person standing on a rocky beach, gazing at the ocean.";
else if (fileName.includes("personwithskylinebackground")) description = "A person walking in front of a city skyline at dusk.";
else if (fileName.includes("personwithballoon")) description = "A person holding a colorful balloon in a park.";
else if (fileName.includes("personbywoodenbridge")) description = "A person walking across a wooden bridge over a small creek.";
else if (fileName.includes("persononmountainridge")) description = "A person standing on the edge of a mountain ridge, enjoying the view.";
else if (fileName.includes("personinfieldofsunflowers")) description = "A person standing in a field of tall sunflowers.";
else if (fileName.includes("personbylakeinwinter")) description = "A person walking by a frozen lake, surrounded by snow-covered trees.";
else if (fileName.includes("personinmediterraneanvillage")) description = "A person walking down a cobblestone street in a Mediterranean village.";
else if (fileName.includes("personwithleaves")) description = "A person walking through a path covered in autumn leaves.";
else if (fileName.includes("persononbikeinforest")) description = "A person cycling through a forest trail with sunbeams filtering through the trees.";
else if (fileName.includes("personindesertlandscape")) description = "A person standing in the middle of a vast desert landscape.";
else if (fileName.includes("personontreebranch")) description = "A person climbing a tree and sitting on a branch.";
else if (fileName.includes("personbymountainriver")) description = "A person sitting near a rushing river in the mountains.";
else if (fileName.includes("personinopenfield")) description = "A person standing in the middle of a wide, open field.";
else if (fileName.includes("personinsnowymountain")) description = "A person skiing down a snow-covered mountain slope.";
else if (fileName.includes("personinstorm")) description = "A person standing in the rain, holding an umbrella.";
else if (fileName.includes("personwithsunshinebackground")) description = "A person walking under the bright sun with clear skies in the background.";
else if (fileName.includes("personwithflowerfield")) description = "A person standing amidst a field of blooming flowers.";
else if (fileName.includes("persononboatintheocean")) description = "A person navigating a small boat across the open ocean.";
else if (fileName.includes("persononclifftopwithview")) description = "A person standing on a clifftop, gazing at the breathtaking view.";
else if (fileName.includes("personbymountainside")) description = "A person resting on the side of a mountain trail.";
else if (fileName.includes("personwithbackgroundsunset")) description = "A person enjoying a sunset view, silhouetted against the sky.";
else if (fileName.includes("personwithwildflowers")) description = "A person standing among colorful wildflowers in a meadow.";
else if (fileName.includes("personbyrainforestwaterfall")) description = "A person standing by a waterfall in a lush rainforest.";
else if (fileName.includes("personundercanopytrees")) description = "A person walking under the canopy of tall trees in the forest.";
else if (fileName.includes("persononmountainpath")) description = "A person hiking along a narrow mountain path.";
else if (fileName.includes("personwithlakeandmountains")) description = "A person standing by a lake, with mountains towering in the background.";
else if (fileName.includes("persononbeachsunset")) description = "A person watching the sunset on a peaceful beach.";
else if (fileName.includes("personbyflowergarden")) description = "A person sitting beside a beautiful flower garden.";
else if (fileName.includes("persononcountryroadwithhorse")) description = "A person walking along a country road with a horse by their side.";
else if (fileName.includes("persononbeachcliffside")) description = "A person standing on a cliffside overlooking the ocean.";
else if (fileName.includes("personinvillagemarket")) description = "A person shopping at a bustling village market.";
else if (fileName.includes("persononcliffsideoverlookingwater")) description = "A person standing at the edge of a cliff, overlooking a serene water body.";
else if (fileName.includes("personwithsnowcappedmountain")) description = "A person enjoying the view of snow-capped mountains from a viewpoint.";
else if (fileName.includes("persononriverbankintrees")) description = "A person sitting on the riverbank surrounded by trees and foliage.";
else if (fileName.includes("personinvalley")) description = "A person walking through a lush green valley surrounded by hills.";
else if (fileName.includes("personondesertdunes")) description = "A person walking across the vast desert dunes at dusk.";
else if (fileName.includes("personwithrainbowbackground")) description = "A person standing under a rainbow in the sky.";
else if (fileName.includes("personinflowerymeadow")) description = "A person walking through a meadow filled with flowers.";
else if (fileName.includes("personinforestclearingsunlight")) description = "A person standing in a forest clearing, with sunlight filtering through the trees.";
else if (fileName.includes("persononbicyclebylake")) description = "A person riding a bicycle along the edge of a lake.";
else if (fileName.includes("persononhighmountainview")) description = "A person gazing at the panoramic view from a high mountain peak.";
else if (fileName.includes("personwalkingonbeachcliffs")) description = "A person walking along a beach with cliffs towering in the background.";
else if (fileName.includes("personwithcitylights")) description = "A person standing in front of the city skyline, with lights glowing in the background.";
else if (fileName.includes("personbywoodlands")) description = "A person standing at the edge of a woodland area.";
else if (fileName.includes("persononmountaintopoverlookingforest")) description = "A person standing on a mountain top, overlooking a dense forest below.";
else if (fileName.includes("personwithforestbackgroundsnow")) description = "A person standing in front of a snow-covered forest backdrop.";
else if (fileName.includes("personinopenmeadowwithmountainview")) description = "A person walking through an open meadow, with mountains in the distance.";
else if (fileName.includes("personinhillsideflowers")) description = "A person walking through a hillside full of blooming flowers.";
else if (fileName.includes("persononmountaintraildaylight")) description = "A person hiking on a mountain trail during the daylight.";
else if (fileName.includes("personwithsunflowerfield")) description = "A person walking through a field of tall sunflowers on a sunny day.";
else if (fileName.includes("persononhorsebackinthemountains")) description = "A person riding horseback through mountainous terrain.";
else if (fileName.includes("personbybrightflowergarden")) description = "A person standing next to a vibrant flower garden in full bloom.";
else if (fileName.includes("personbydesertcactus")) description = "A person standing near a cactus in the desert landscape.";
else if (fileName.includes("personinbambooforest")) description = "A person walking through a bamboo forest with sunlight streaming in.";
else if (fileName.includes("personatdesertedge")) description = "A person standing at the edge of a vast desert landscape.";
else if (fileName.includes("personwithdesertcanyon")) description = "A person standing on a canyon edge in a desert landscape.";
else if (fileName.includes("persononrockyoutcrop")) description = "A person standing on a rocky outcrop, looking at the surrounding landscape.";
else if (fileName.includes("personinthegreenfield")) description = "A person walking through a lush green field on a bright day.";
else if (fileName.includes("personatlookoutpoint")) description = "A person standing at a lookout point, overlooking a valley.";
else if (fileName.includes("persononhikingpathwithclouds")) description = "A person hiking on a mountain path with clouds surrounding the peak.";
else if (fileName.includes("personwithgreenerybackground")) description = "A person standing in front of a lush green forest backdrop.";
else if (fileName.includes("persononcampusgrass")) description = "A person sitting on the grass in a university campus.";
else if (fileName.includes("persononbeachonbrightday")) description = "A person walking along the beach on a bright, sunny day.";
else if (fileName.includes("persononsidewalk")) description = "A person walking on a busy sidewalk in an urban area.";
else if (fileName.includes("personbylargewaterfall")) description = "A person standing near a large waterfall, feeling the mist.";
else if (fileName.includes("personwalkingbyriverbank")) description = "A person walking along a riverbank with trees lining the shore.";
else if (fileName.includes("persononhighway")) description = "A person walking along a highway with mountains in the distance.";
else if (fileName.includes("persononwalkinginforest")) description = "A person walking along a forest path.";


    
    lookupArea.innerHTML = description;
  }, 1000);
}
